### ISSUE TITLE
whisper--check-install-and-run needs manual installation and patch on Win10.

### ISSUE THREAD

**Issue by ujikol** [natrys/whisper.el#10]
The way (defun whisper--check-install-and-run) is implemented does not work on Win10.

My workaround is to install whisper.cpp and model manually and patch:
(defun whisper--check-install-and-run (buffer status)
  (whisper--record-audio))

**Comment by natrys** [comment]
You can now set `whisper-install-whispercpp` to `'manual` to skip over automatic installation (assuming you have manually installed it in `whisper-install-directory`). That should remove the need to do patching.
