### ISSUE TITLE
Instructions to granting Mic access to Emacs seem outdated (atleast for macos 14.1.1)

### ISSUE THREAD

**Issue by ManasJayanth** [natrys/whisper.el#18]
The SQL query that currently reads,

```
insert into access values  ('kTCCServiceMicrophone','org.gnu.Emacs', 0, 2, 2, 1, null, null, null, 'UNUSED', null, 0, strftime('%s', 'now'));
```

could be,

```
insert into access values  ('kTCCServiceMicrophone','org.gnu.Emacs', 0, 2, 2, 1, null, null, null, 'UNUSED', null, 0, strftime('%s', 'now'),null, null, 'UNUSED', 0);
```

This is what worked for me.

**Comment by natrys** [comment]
Thanks, I have updated the wiki page. I can't seem to find any changelog for TCC.db schema so I am thankful for feedback like yours as I am not a MacOS user myself.

**Comment by g-simmons** [comment]
The step here might be useful:

https://github.com/rksm/org-ai?tab=readme-ov-file#1-allow-emacs-to-record-audio
