### ISSUE TITLE
No integers for whisper quantize

### ISSUE THREAD

**Issue by jasoninja** [natrys/whisper.el#23]
Whisper-quantize is looking for an integer, but there aren’t any integers given in the documentation, just strings, q4_01, etc.

**Comment by natrys** [comment]
It shouldn't be looking for an integer, indeed the correct value is a string as noted in doc string. Not sure why it's not working for you. 

Note that if you are actually trying `q4_01` as you say, that's not a valid value. Instead try: `q4_1`. Basically:

```elisp
(setq whisper-quantize "q4_1")
```

(it seems whisper.cpp added a bunch of `q*_k` options so I need to add those as well, but that shouldn't be relevant here)

**Comment by jasoninja** [comment]
![IMG_1637](https://github.com/natrys/whisper.el/assets/2892212/4697a6ef-b336-4fbd-a2ce-850ca3117141)

**Comment by jasoninja** [comment]
When I do an apropos search for whisper-quantize, it has (custom-type (choice integer (const nil)) in its plist.

**Comment by jasoninja** [comment]
Which is in line 108 of whisper.el.

**Comment by jasoninja** [comment]
So if I just change integer to string, it should work?
