### ISSUE TITLE
if: Speech recognition model medium-q5_0 not recognised. For the list, see: https://github.com/ggerganov/whisper.cpp/tree/master/models

### ISSUE THREAD

**Issue by liar666** [natrys/whisper.el#29]
Hello,

I was using `Whisper.el`/`Whisper.cpp` with quantized models (`medium` in particular) without any problem until recently.

I `git pull`ed `Whisper.cpp` last week and discovered there are new models (large-turbo, distill, etc.). And that `Whisper.el` was supposed to have been updated accordingly.

Unfortunately I cannot manage to adapt my configuration to make it work with recent changes in `Whisper.el`/`Whisper.cpp` .

My configuration looks like:
```
(use-package! whisper
  :load-path
    "~/.doom.d/packages/whisper.el"
  :bind
   ("C-S-r" . #'whisper-run)
   ("C-S-t" . #'toggle-language-whisper)
  :config
    (setq
      whisper-install-directory "~/.doom.d/packages/"
      whisper-model "medium" ;;; <<--- WAS "medium-q5_q"
      ;; whisper-quantize "q5_0" ;;; <<--- WAS NOT THERE, DOES NOT HELP
      whisper-translate nil
      whisper--ffmpeg-input-format "pulse"
      whisper--ffmpeg-input-device "default" ; -ar 16000 -ac 1 -c:a pcm_s16le
      )
    (setq whisper-language "en") ; (setq whisper-language "fr")
)
```
When I run `whisper-run`, it uses the `medium` model. When I change back `whisper-model "medium"` to `whisper-model "medium-q5_0" `, I get error:
`if: Speech recognition model medium-q5_0 not recognised. For the list, see: https://github.com/ggerganov/whisper.cpp/tree/master/models`

Indeed, `medium-q5_0` is not listed in the models on page `https://github.com/ggerganov/whisper.cpp/tree/master/models`, which are the ones you can directly download, but you can create it locally from `medium` as explained in `Whisper.cpp` README.

So, am I wrong and is `medium-q5_0` not supported at all and not supposed to be generated locally? Or did I miss something new in the `Whisper.el` (other than `whisper-quantize`) that could allow me to run quantized model?

**Comment by liar666** [comment]
> Just to remove misunderstanding, you should set whisper-model to "medium" and whisper-quantize to "q5_0", and that should download medium model and locally quantize it (create 539M ggml-medium-q5_0.bin). Is it not happening?

When I do that I get error `Speech recognition model "medium" isn't available, download now? (y or n) `.

- If I say `n` (my default choice until now since I already quantized the model, I removed the non-quantized version) => error "you need a model"
- If I say `y` it downloads the model, but I'm not sure if it quantizes it (does not says anything about quantization and it does not take much time after download to ask if I want to use it now). Also transcription is slow, so I assume it still uses "medium", not "medium-q5_0" 

If I remove again "medium", then I get the error again.

Based on that I assume that quantization does not occur and quantized model is not used...

Is there a way to now which model is used in the end? (I tried to `lsof -t <models>` while transcribing, but with no success)

**Comment by natrys** [comment]
Make sure you are using most recent commit of whisper.el too.

You can check your `whisper.cpp/models` folder and look at files sorted by modified time. As I said there should be most recently created ggml-medium-q5_0.bin file (~539MB size).

You could also use system wide observability tools like [forkstat](https://github.com/ColinIanKing/forkstat) too see which process is being spawned in background (`sudo forkstat -e exec`), then look at the whisper.cpp command that's being run which should include model path. On Emacs side it's also possible to check for processes that had been spawned in elisp by doing `M-x list-processes`. You have to do it exactly during transcription, not before (like during recording) or after.

The "q5_k" is probably fractionally faster, but either way medium models aren't exactly fast even when quantized.

**Comment by liar666** [comment]
Thank first for your quick answer!

> Make sure you are using most recent commit of whisper.el too.
I have it. 
```
~/.doom.d/packages/whisper.el$ git pull
Already up to date.
```
```
(use-package! whisper
  :load-path
    "~/.doom.d/packages/whisper.el"
...
```

> You can check your `whisper.cpp/models` folder and look at files sorted by modified time. As I said there should be most recently created ggml-medium-q5_0.bin file (~539MB size).

The date of the quantized model corresponds to the one I quantize myself a few days ago, not the date I ran whisper.el to download the model (today).

> You could also use system wide observability tools like [forkstat](https://github.com/ColinIanKing/forkstat) too see which process is being spawned in background (`sudo forkstat -e exec`), then look at the whisper.cpp command that's being run which should include model path. On Emacs side it's also possible to check for processes that had been spawned in elisp by doing `M-x list-processes`. You have to do it exactly during transcription, not before (like during recording) or after.

I'll try that.

> The "q5_k" is probably fractionally faster, but either way medium models aren't exactly fast even when quantized.

I assume it depends on the machine you have. I'm (very) fortunate to have a Dell with XEON + NVIDIA. "medium" model works quite fast here :)

**Comment by liar666** [comment]
Hi,
Thanks again for your quick help.
Seems that this last technique (removing the q5_0 version and letting whisper.el regenerate it) has worked!
Thanks you!
