### ISSUE TITLE
cloned and built whisper.cpp directory not found

### ISSUE THREAD

**Issue by wg-daniel** [natrys/whisper.el#31]
First of all , thanks for your work on this! Really looking forward to giving it a spin.

I've tried to get it up and running, however, I've been running into an install/build loop.

```
Couldn't find whisper.cpp, install it at: /home/user/.config/emacs/.local/cache/.cache/whisper.cpp/ ? (y or n) y
Quit
Compilation finished
Couldn't find whisper.cpp, install it at: /home/user/.config/emacs/.local/cache/.cache/whisper.cpp/ ? (y or n) y
Compilation exited abnormally with code 128
Couldn't find whisper.cpp, install it at: /home/user/.config/emacs/.local/cache/.cache/whisper.cpp/ ? (y or n) y
Compilation exited abnormally with code 128
Couldn't find whisper.cpp, install it at: /home/user/.config/emacs/.local/cache/.cache/whisper.cpp/ ? (y or n) n
error in process sentinel: whisper--check-install-and-run: Needs whisper.cpp to be installed
error in process sentinel: Needs whisper.cpp to be installed
```

```sh
ls .config/emacs/.local/cache/.cache/
whisper.cpp
````
It clones successfully, builds successfully, seeing the `main` file in `build/bin`. But then just doesn't recognize the cloned directory anymore after compilation. :shrug: 

I've been trying to grasp where the culprit could be, but I guess my lisp-fu isn't good enough yet to find the culprit.

**Comment by natrys** [comment]
Can you share your config? In particular, what are you setting `whisper-install-directory` to? If you are not touching the default, what's the current value of that variable?

**Comment by wg-daniel** [comment]
Yep that seems to be it. Got it working now.

Thank you very much for your time!
