### ISSUE TITLE
whisper-file fails on Fedora 38 (pipewire-pulse)

### ISSUE THREAD

**Issue by oatmealm** [natrys/whisper.el#4]
Hi. I'm able to run this from the command line on Fedora 38, so `PipeWire` with `pipewire-pulse` installed and working.

```
ffmpeg -i in.mp3 -ar 16000 -y temp.mp3
```

`whisper-file` fails with:

```
[*] Pre-processing media file
error in process sentinel: FFmpeg command failed to record audio [2 times]
```

`whisper-run` works amazingly well recording and transcribing.

**Comment by natrys** [comment]
Pipewire (or audio server in general) should not be relevant for file operation. Your first command is indeed what whisper.el tries to do at first, but whether or not it works depends on whether ffmpeg was built with correct libraries for codecs, I think.

So, was the file you were trying to transcribe also an mp3 or was it some other format? Does that command work in terminal when you replace `in.mp3` with the path to the actual file you are interested in?

**Comment by oatmealm** [comment]
hi @natrys ! yes, it was mp3 (192 kbps, 44100Hz, from what I can see). 
No, it doesn't work with either files....

**Comment by natrys** [comment]
> No, it doesn't work with either files....

Do you mean that for whisper.el or ffmpeg in the terminal? If it's the latter, is there anything distinctive in the error message?

**Comment by oatmealm** [comment]
> Do you mean that for whisper.el

Yes for whisper.el. Ffmpeg converts the file successfully

**Comment by oatmealm** [comment]
BTW, why is it saying "FFmpeg command failed to record audio" ... does it refer to the conversion?

**Comment by natrys** [comment]
Yeah that's a mistake. Should be fixed now, thanks.

Unfortunately I don't really have any ideas here as it seems to work for me for any valid file. 

Only way we can make sense of this is if we can see the ffmpeg error log, which unfortunately isn't retained by default to avoid buffer clutter.

If you are still inclined to investigate, you could specify a buffer to contain stderr log of the failing ffmpeg process, and then inspect its content. For that you would need to add one line to the `whisper--record-audio` function:

``` diff
diff --git a/whisper.el b/whisper.el
index 3895a7a..2d8d770 100644
--- a/whisper.el
+++ b/whisper.el
 (defun whisper--record-audio ()
   "Start audio recording process in the background."
   (with-current-buffer whisper--point-buffer
     (setq whisper--marker (point-marker)))
   (if whisper--ffmpeg-input-file
       (message "[*] Pre-processing media file")
     (message "[*] Recording audio"))
   (setq whisper--recording-process
         (make-process
          :name "whisper-recording"
          :command (whisper--record-command whisper--temp-file)
+         :stderr (get-buffer-create "*whisper-test*")
          :connection-type nil
          :buffer nil
          :sentinel (lambda (_process event)
                      (cond ((or (string-equal "finished\n" event)
                                 ;; this is would be sane
                                 (string-equal "terminated\n" event)
                                 ;; but this is reality
                                 (string-equal "exited abnormally with code 255\n" event))
                             (whisper--transcribe-audio))
                            ((string-equal "exited abnormally with code 1\n" event)
                             (if whisper--ffmpeg-input-file
                                 (error "FFmpeg failed to convert given file")
                               (error "FFmpeg failed to record audio"))))))))
 ```

 and then re-evaluate the function, run the test, and then see what the `*whisper-test*` buffer says.

**Comment by oatmealm** [comment]
There's also `file-truename` which I believe also resolve symbolic links...

Thank you!

**Comment by oatmealm** [comment]
Yep. Working ! It'll take sometime I'm guessing :)
